table fact_sales_info
	lineageTag: 66eb9a9e-984a-4916-895f-6421527925b9

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e6a8e24-8dff-442d-9866-5a6cbf16bccd
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column sale_id
		dataType: string
		lineageTag: 1aa43d0e-b3f5-4359-9f86-1cd54d708844
		summarizeBy: none
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: string
		lineageTag: e8fb4984-c653-4b41-b3e6-07948c6b6402
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 22028088-8294-4bb3-9779-389a62e4e883
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column units
		dataType: int64
		lineageTag: ce8008f8-01c3-4207-b021-6b1ea58c2a58
		summarizeBy: sum
		sourceColumn: units

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_price
		dataType: double
		lineageTag: 1cc5c46f-5d61-4635-810b-b2dc5608cc5b
		summarizeBy: sum
		sourceColumn: product_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_cost
		dataType: double
		lineageTag: f36e11fe-e0e3-4abf-9016-5fb9a392f751
		summarizeBy: sum
		sourceColumn: product_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue
		dataType: double
		lineageTag: bf1b6b7f-1921-4304-8b1b-d7b0f27e1434
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cogs
		dataType: double
		lineageTag: d9a1311f-cf16-4f05-bbaf-63cf1c077e76
		summarizeBy: sum
		sourceColumn: cogs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column stock_partitioned
		dataType: double
		lineageTag: 605ace1c-b668-476a-9413-2aeed78f679d
		summarizeBy: sum
		sourceColumn: stock_partitioned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column has_stock
		dataType: int64
		formatString: 0
		lineageTag: 221da179-2485-47c3-b68c-43db4ffeb455
		summarizeBy: sum
		sourceColumn: has_stock

		annotation SummarizationSetBy = Automatic

	partition fact_sales_info = m
		mode: import
		source =
				let
				    QUERY = " SELECT * FROM " & SchemaName_Postgres & "." & "fact_sales_info",
				    Fonte = Value.NativeQuery(PostgreSQL.Database("localhost", "dbt_sources"), QUERY, null, [EnableFolding=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"sale_id", type text}, {"store_id", type text}, {"product_id", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

